# Configuration section.
# "template" and "resource" are required.
---
# Command templates.
# {param} to replace by value: {param} -> value
# [param] to replace by key and value: [param] -> --key value
# param not specified with either {param} and [param], but appearing in param choice will only
# affect {_name} and {_output}
# reserved params:
# {_name}: name of param choices
# {_output}: /{--output}/{_name}
# {_datetime}: current date&time
template:
  base: >
    echo command {curl} [bracket] {_datetime} {_name} {_output}
  replace: >
    echo command [alias_replace]
  remap: >
    echo command [alias_remap]
  pack: >
    echo command {curl} [bracket]

# replace param to group of new params.
# Applicable only for [param]s
alias:
  # alias_replace=1 will results in alias_replaced1=alias_replaced2=1
  alias_replace: [ alias_replaced1, alias_replaced2 ]

  # alias_remap=remap1 will be replaced as alias_remap_new_bracket1=1, remap_new_bracket2=2
  alias_remap: # remap
    remap1: { alias_remap_new_bracket1: 1, alias_remap_new_bracket2: 2 }

# fill in values to group of params specified in the command.
# pack params(in this example, pack_replace and pack_remap) should not be specified in command.
pack: # pack
  # pack_replace=1 will results in curl=bracket=1
  pack_replace: [ curl, bracket ]
  # pack_remap=remap1 will be replaced as curl=1, bracket=2
  pack_remap:
    remap1: { curl: 1, bracket: 2 }


default:
  curl: 0
  bracket: 0
  alias_replace: 1
  alias_remap: remap1


# gpu indices to be filled in CUDA_VISIBLE_DEVICES={}. each resource is assigned to a worker.
# for multi-gpu tasks, simply set [ "1,2", "3,4" ]
# a single resource can be assigned multiple times, typically when your task requires a very low gpu utilization
# [ "1", "2", "3", "1", "2", "3" ]
resource: [ "1" , "2" ]

# list all possible choices here, model_tuner.py will sweep all possible combinations.
---
_title: base
curl: [ 1 ]
bracket: [ 1 ]

---
_title: missed
curl: [ 1 ]

---
_title: missed_and_dummy
dummy: [ 1 ]

---
_title: replace
replace: [ 1 ]

---
_title: remap
remap: [ remap1 ]

---
_title: pack_replace
pack_replace: [ 1 ]

---
_title: pack_remap
pack_remap: [ remap1 ]
